export enum StackingContextType {
  DEFAULT,
  POSITIONED_WITH_ZINDEX,
  FLEX_ITEM_WITH_Z_INDEX_OTHER_THAN_AUTO,
  OPACITY_LESS_THAN_ONE,
  TRANSFORM_OTHER_THAN_NONE,
  MIX_BLEND_MODE_OTHER_THAN_NORMAL,
  FILTER_OTHER_THAN_NONE,
  ISOLATION_ISOLATE,
  FIXED_POSITIONED_WEBKIT_AND_CHROME22,
  WEBKIT_OVERFLOW_SCROLLING_TOUCH,
}
